/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DoctorRole;

import Business.Appointment.Appointment;
import Business.Employee.Employee;
import Business.Patient.Patient;
import javax.swing.JPanel;

/**
 *
 * @author preranaurs
 */
public class CompletedBillingJPanel extends javax.swing.JPanel {

    /**
     * Creates new form MarkForBillingJPanel
     */
    private JPanel userProcesscontainer;
    private Patient patient;
    private Appointment appointment;
    private Employee doctor;
    private Employee receptionist;
    

    CompletedBillingJPanel(JPanel userProcessContainer, Patient patient, Appointment appointment, Employee doctor, Employee receptionist) {
        initComponents();
        this.userProcesscontainer = userProcessContainer;
        this.patient = patient;
        this.appointment = appointment;
        this.doctor = doctor;
        this.receptionist = receptionist;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        jLabel1.setText("Doctor Bill");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(333, 333, 333)
                .addComponent(jLabel1)
                .addContainerGap(501, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel1)
                .addContainerGap(535, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
