/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageAirliner;

import Business.Airliner;
import Business.AirlinerDirectory;
import Business.Fleet;
import Business.Flight;
import Business.FlightSchedule;
import UserInterface.AdminTravelAgencyRole.TravelAgencyMain;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aditi
 */
public class ManageAirlinersJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageAirlinersJPanel
     */
    AirlinerDirectory airlinerdirectory;
    javax.swing.JPanel UserProcessContainer;
    List<FlightSchedule> flightScheduleList;
   Fleet airplaneDir;
   List<Flight> flightList;

    
public ManageAirlinersJPanel(javax.swing.JPanel spane, AirlinerDirectory airlinerDir, Fleet airplanelist, List<Flight> flightList, List<FlightSchedule> flightScheduleList) {
    initComponents();
    UserProcessContainer = spane;
    airlinerdirectory = airlinerDir;
    this.airplaneDir=airplanelist;
    this.flightScheduleList = flightScheduleList;
    this.flightList=flightList;
    if(!airlinerdirectory.getAirlinerList().isEmpty()){
    populateAirlinerList();
    }
        
    
}

   

    

    public void populateAirlinerList()
    {
        //populateFromFile();
        //using airlinerDirectory populate table
        DefaultTableModel model = (DefaultTableModel) tblAirliner.getModel();
        model.setRowCount(0);
        for (Airliner s : airlinerdirectory.getAirlinerList()) {
            Object row[] = new Object[1];
            row[0] = s;
            model.addRow(row);
        }
    }
    
 
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAirliner = new javax.swing.JTable();
        btnNewAirliner = new javax.swing.JButton();
        btnViewAirliner = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnmngAirplane = new javax.swing.JButton();
        btnMngFlight = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Manage Airliners");

        tblAirliner.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Airliner"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblAirliner);

        btnNewAirliner.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnNewAirliner.setText("New Airliner");
        btnNewAirliner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewAirlinerActionPerformed(evt);
            }
        });

        btnViewAirliner.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnViewAirliner.setText("View Airliner");
        btnViewAirliner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAirlinerActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnBack.setText("<Back");
        btnBack.setToolTipText("");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnmngAirplane.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnmngAirplane.setText("Manage Airplane");
        btnmngAirplane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmngAirplaneActionPerformed(evt);
            }
        });

        btnMngFlight.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnMngFlight.setText("Manage Flights");
        btnMngFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMngFlightActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(btnBack)
                .addGap(131, 131, 131)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jLabel1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnNewAirliner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnmngAirplane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnViewAirliner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMngFlight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(201, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnNewAirliner)
                            .addComponent(btnViewAirliner)))
                    .addComponent(btnBack))
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnmngAirplane)
                    .addComponent(btnMngFlight))
                .addContainerGap(128, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewAirlinerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAirlinerActionPerformed
        // TODO add your handling code here:
        int row = tblAirliner.getSelectedRow();
        if(row<0){
            JOptionPane.showMessageDialog(null, "Please select a row!!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Airliner airliner = (Airliner)tblAirliner.getValueAt(row,0);
        AirlinerDirectory ad = airlinerdirectory;
        //UserProcessContainer.removeAll();
        ViewAirlinerJPanel msjp = new ViewAirlinerJPanel (UserProcessContainer,airliner, ad, airplaneDir, flightList);
        UserProcessContainer.add("ViewAirlinerJPanel",msjp); //any name will do
        ((java.awt.CardLayout)UserProcessContainer.getLayout()).next(UserProcessContainer);
        
    }//GEN-LAST:event_btnViewAirlinerActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        
        AirlinerDirectory ad = airlinerdirectory;
        //UserProcessContainer.removeAll();
        //TravelAgencyMain msjp = new TravelAgencyMain (UserProcessContainer, ad);
        //UserProcessContainer.add("CreateNewAirlinerJPanel",msjp); //any name will do
       // ((java.awt.CardLayout)UserProcessContainer.getLayout()).next(UserProcessContainer);
        
        
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnmngAirplaneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmngAirplaneActionPerformed
        // TODO add your handling code here:
        //get the airliner name to manage
        int row = tblAirliner.getSelectedRow();
        if(row<0){
            JOptionPane.showMessageDialog(null, "Please select a row!!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Airliner airliner = (Airliner)tblAirliner.getValueAt(row,0);
        
        
        AirlinerDirectory ad = airlinerdirectory;
        //UserProcessContainer.removeAll();
        ManageAirplaneJPanel msjp = new ManageAirplaneJPanel (UserProcessContainer, airliner,ad, airplaneDir);
        UserProcessContainer.add("ManageAirplaneJPanel",msjp); //any name will do
        ((java.awt.CardLayout)UserProcessContainer.getLayout()).next(UserProcessContainer);
        
        
        
    }//GEN-LAST:event_btnmngAirplaneActionPerformed

    private void btnNewAirlinerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewAirlinerActionPerformed
        
        //goto CreateNewAirlinerJPanel
        
        AirlinerDirectory ad = airlinerdirectory;
        //UserProcessContainer.removeAll();
        CreateNewAirlinerJPanel msjp = new CreateNewAirlinerJPanel (UserProcessContainer, ad);
        UserProcessContainer.add("CreateNewAirlinerJPanel",msjp); //any name will do
        ((java.awt.CardLayout)UserProcessContainer.getLayout()).next(UserProcessContainer);
        
        
    }//GEN-LAST:event_btnNewAirlinerActionPerformed

    private void btnMngFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMngFlightActionPerformed
        // TODO add your handling code here:
        
        int row = tblAirliner.getSelectedRow();
        if(row<0){
            JOptionPane.showMessageDialog(null, "Please select a row!!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Airliner airliner = (Airliner)tblAirliner.getValueAt(row,0);
        
        AirlinerDirectory ad = airlinerdirectory;
        //UserProcessContainer.removeAll();
        ManageFlightJPanel msjp = new ManageFlightJPanel (UserProcessContainer, airliner, ad, flightList,flightScheduleList);
        UserProcessContainer.add("ManageFlightJPanel",msjp); //any name will do
        ((java.awt.CardLayout)UserProcessContainer.getLayout()).next(UserProcessContainer);
        
        
        
        
    }//GEN-LAST:event_btnMngFlightActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnMngFlight;
    private javax.swing.JButton btnNewAirliner;
    private javax.swing.JButton btnViewAirliner;
    private javax.swing.JButton btnmngAirplane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAirliner;
    // End of variables declaration//GEN-END:variables
}
